### ISSUE TITLE
This repo lacks a license

### ISSUE THREAD

**Issue by comradekingu** [CaptainFact/captain-fact-data#1]

**Comment by Betree** [comment]
Hello @comradekingu, thanks for opening this. There's no root license cause it depends on the data being shared.

There's a CC license for Wikidata to respect the original one and I've just copied the main AGPL3 licenses to https://github.com/CaptainFact/captain-fact-dev-data/tree/master/Database to cover this folder.

Does that solve the issue for you?

**Comment by comradekingu** [comment]
Yes :) Now the claim of all code being libre software is undisputed.
